from enum import StrEnum
from typing import Any, Generic, TypeVar

from pydantic import BaseModel

from .base import ResponseParser
from .response_format import ResponseFormatCapability


def _make_schema_strict(schema: dict[str, Any]) -> dict[str, Any]:
    # Process Definitions ($defs) generated by Pydantic for nested models
    if "$defs" in schema:
        for def_schema in schema["$defs"].values():
            _make_schema_strict(def_schema)

    # Process Objects
    if schema.get("type") == "object" or "properties" in schema:
        schema["additionalProperties"] = False
        properties = schema.get("properties", {})

        # OpenAI requires ALL properties to be required when strict=True
        if properties:
            schema["required"] = list(properties.keys())

            # Recursively process each property
            for prop_schema in properties.values():
                _make_schema_strict(prop_schema)

    # Process Arrays
    elif schema.get("type") == "array" and "items" in schema:
        _make_schema_strict(schema["items"])

    # Process Unions (anyOf / allOf)
    for key in ["anyOf", "allOf"]:
        if key in schema:
            for sub_schema in schema[key]:
                _make_schema_strict(sub_schema)

    return schema


class JsonResponseFormat(StrEnum):
    no = "no"
    json = "json"
    json_schema = "json_schema"


TResult = TypeVar("TResult", bound=BaseModel)


class JsonParser(ResponseParser[TResult], Generic[TResult]):
    def __init__(self, model_type: type[TResult], response_format: JsonResponseFormat) -> None:
        self._model_type = model_type
        self._format = response_format

    @property
    def returns(self) -> type[TResult]:
        return self._model_type

    def validate(self, content: str) -> TResult:
        return self._model_type.model_validate_json(content)

    def to_response_format(self, capabilities: set[ResponseFormatCapability]) -> dict | None:
        if self._format == JsonResponseFormat.json_schema and ResponseFormatCapability.json_schema in capabilities:
            return {
                "type": "json_schema",
                "json_schema": {
                    "name": self._model_type.__name__,
                    "strict": True,
                    "schema": _make_schema_strict(self._model_type.model_json_schema()),
                },
            }
        elif (
            self._format in {JsonResponseFormat.json_schema, JsonResponseFormat.json}
            and ResponseFormatCapability.json in capabilities
        ):
            return {"type": "json_object"}

        return None
